version: '3.4'

services:
  redis-cache-test:
    image: redis:alpine

  rabbitmq-test:
    image: rabbitmq:3-management-alpine

  envoy-proxy-test:
    image: envoyproxy/envoy:v1.16-latest

  investor-service-test:
    image: ${REGISTRY:-aham}/investor-service-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Investor/Investor.API/Dockerfile
    depends_on:
      - redis-cache-test
      - rabbitmq-test
